[package]
name = "block-pulse"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = "2.0.14"
tokio = { version = "1.38.0", features = ["full"] }
eyre = "0.6.12"
serde = { version = "1.0.203",features = ["derive"] }